<b><h1> Gauss Elimination</h1> </b> 

In [10]:
#Gauss Elimination :
import numpy as np
# A =  [Persamaan 1 ], [persamaan 2] , [ Persamaan 3]
# b = [Jawaban1 , jawaban2 , jawaban3]

A = np.array([[1, 1, -2, 1, 3, -1], [2, -1, 1, 2, 1, -3], [1, 3, -3, -1, 2, 1], [5, 2, -1, -1, 2, 1], [-3, -1, 2, 3, 1, 3], [4, 3, 1, -6, -3, -2]], dtype='float')
b = np.array([4, 20, -15, -3, 16, -27])

Ab = np.hstack([A, b.reshape(-1, 1)])

n = len(b)

for i in range(n):
    a = Ab[i]

    for j in range(i + 1, n):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]

    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

x = Ab[:, :]
# [ [x1 x2 x3 jawaban]
print(x)

[[            nan             nan             nan             nan
              nan             nan             nan]
 [            nan             nan             nan             nan
              nan             nan             nan]
 [ 0.00000000e+00 -9.72965405e-17  1.00000000e+00  0.00000000e+00
  -2.11471052e-17  0.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -6.94975289e-19  0.00000000e+00  1.00000000e+00
  -2.46716228e-17  0.00000000e+00  4.00000000e+00]
 [-0.00000000e+00 -5.42080726e-17 -0.00000000e+00 -0.00000000e+00
   1.00000000e+00 -0.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00 -6.94975289e-18  0.00000000e+00  0.00000000e+00
   1.25757433e-17  1.00000000e+00 -1.00000000e+00]]


c:\users\acer\anaconda3\envs\tf-gpu\lib\site-packages\ipykernel_launcher.py:27: RuntimeWarning: divide by zero encountered in double_scalars
c:\users\acer\anaconda3\envs\tf-gpu\lib\site-packages\ipykernel_launcher.py:28: RuntimeWarning: invalid value encountered in multiply


<b><h1> LU Decompostition Pivot</h1> </b> 

In [2]:
# LU Decompostition Method
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

#UBAH DISINI
#LU with pivoting, hasilnya mestinya sama aja 
A = scipy.array([ [4, -2, 1], [-2, 4, -2], [1, -2, 4] ])
P, L, U = scipy.linalg.lu(A)

print ("A:")
pprint.pprint(A)

print ("P:")
pprint.pprint(P)

print ("L:")
pprint.pprint(L)

print ("U:")
pprint.pprint(U)

print(np.matmul(L,U))

A:
array([[ 4, -2,  1],
       [-2,  4, -2],
       [ 1, -2,  4]])
P:
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
L:
array([[ 1.  ,  0.  ,  0.  ],
       [-0.5 ,  1.  ,  0.  ],
       [ 0.25, -0.5 ,  1.  ]])
U:
array([[ 4. , -2. ,  1. ],
       [ 0. ,  3. , -1.5],
       [ 0. ,  0. ,  3. ]])
[[ 4. -2.  1.]
 [-2.  4. -2.]
 [ 1. -2.  4.]]


<b><h1> Gauss - Seidel iterative method </h1> </b> 

In [1]:
# Gauss-Seidel iterative Method
import numpy as np

def Gauss_Seidel(A, b, error_s):
	[m, n] = np.shape(A)

	U = np.triu(A, 1)
	L = np.tril(A)
	iteration = 0 
	x = np.ones((m,1))
	err = np.ones((m,1))*100

	while np.max(err) > error_s:

		xn = np.dot(np.linalg.inv(L), (b - np.dot(U, x)))
		err = abs((xn - x)/xn)*100
		x = xn
		iteration = iteration + 1 

	for i in range(0, m):
		print ('x[%0.0f] = %6.4f --- Error: %0.4f %%' % (i+1, x[i], err[i]))
	return(iteration)


# A nya matrix 3x3
# b nya jawabannya
# UBAH DISINI
A = np.array(np.mat('1, 2, 5, 1 ; 3, -4, 3, -2 ; 4, 3, 2, -1 ; 1, -2, -4, -1'))
				     	
b = np.array(np.mat('4 ; 7 ; 1 ; 2'));

# Approximate % error stop criterion
error_s = 10

a = Gauss_Seidel(A, b, error_s)
print("Iteration = ",a)

x[1] =    nan --- Error: nan %
x[2] =    inf --- Error: nan %
x[3] =   -inf --- Error: nan %
x[4] =    nan --- Error: nan %
Iteration =  676


c:\users\acer\anaconda3\envs\tf-gpu\lib\site-packages\ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()


<b><h1> Lagrange Interpolation</h1> </b> 

In [6]:
import numpy as np
from pypoly import Polynomial

def chunkIt(seq, num):
    avg = len(seq) / float(num)
    out = []
    last = 0.0
    while last < len(seq):
        out.append(seq[int(last):int(last + avg)])
        last += avg
    return out

def product(list):
    p = 1
    for i in list:
        p *= i
    return p

def Lagrange(x,X):
    T = np.zeros((2,len(X)))
    list = []
    for i in range(len(X)):
        for j in range(len(X)):
            if i != j:
                list.append((x-X[j][0])/(X[i][0]-X[j][0]))
    p = []
    for i in chunkIt(list,len(X)):
        p.append(product(i))
    for i in range(len(X)):
        T[0][i] = p[i]
        T[1][i] = X[i][1]

    list2 = []
    for i in range(len(X)):
        list2.append(T[0][i]*T[1][i])
    return sum(list2)
# Input 
# x kecil buat mau dicari nilai brpa ( misal soalnya tau ln1 sama ln2 , disuru cari ln3 berarti x kecil = 3)
# X gede [x,y]
#Change HERE
x, X = 1, [[0,7],[2,11],[3,28]]

order = len(X)
equations = np.array([[point[0] ** i for i in range(order)] for point in X])
values = np.array([point[1] for point in X])
coefficients = np.linalg.solve(equations, values)
print ('coefficients', list(coefficients))
p = Polynomial(*coefficients)

print(p)
# p hasilnya , p(x) fungsi hasil interpolasi nya
print(p(x))
#print(Lagrange(x,X)) --> sama aja kyk p mestinya

coefficients [7.0, -8.000000000000002, 5.000000000000001]
7 - 8 * X + 5 * X**2
3.999999999999999


In [5]:
import numpy as np
from pypoly import Polynomial

def chunkIt(seq, num):
    avg = len(seq) / float(num)
    out = []
    last = 0.0
    while last < len(seq):
        out.append(seq[int(last):int(last + avg)])
        last += avg
    return out

def product(list):
    p = 1
    for i in list:
        p *= i
    return p

def Lagrange(x,X):
    T = np.zeros((2,len(X)))
    list = []
    for i in range(len(X)):
        for j in range(len(X)):
            if i != j:
                list.append((x-X[j][0])/(X[i][0]-X[j][0]))
    p = []
    for i in chunkIt(list,len(X)):
        p.append(product(i))
    for i in range(len(X)):
        T[0][i] = p[i]
        T[1][i] = X[i][1]

    list2 = []
    for i in range(len(X)):
        list2.append(T[0][i]*T[1][i])
    return sum(list2)
# Input 
# x kecil buat mau dicari nilai brpa ( misal soalnya tau ln1 sama ln2 , disuru cari ln3 berarti x kecil = 3)
# X gede [x,y]
#Change HERE
x, X = 0.5, [[-1.2, -5.5],[0.3, -5.39],[1.1, -3.4],[1.4, -2.3]]

order = len(X)
equations = np.array([[point[0] ** i for i in range(order)] for point in X])
values = np.array([point[1] for point in X])
coefficients = np.linalg.solve(equations, values)
print ('coefficients', list(coefficients))
p = Polynomial(*coefficients)

print(p)
# p hasilnya , p(x) fungsi hasil interpolasi nya
print(p(x))
#print(Lagrange(x,X)) --> sama aja kyk p mestinya

coefficients [-5.7864682274247485, 1.0064117766291667, 1.0479198337893987, 0.008589236850107386]
-5.78647 + 1.00641 * X + 1.04792 * X**2 + 0.00858924 * X**3
-5.020208726056552


<b><h1> Newton’s Raphson Method</h1> </b> 

In [13]:
# Python3 code for implementation of Newton 
# Raphson Method for solving equations 

# An example function whose solution 
# is determined using Bisection Method. 
# The function is x **2 - 7*x -7

def func( x ): 
    
    #CHANGE HERE
	return x **3 - 2*x**2 + 3*x + 200

# Derivative of the above function 
# which is 3*x^x - 2*x 
def derivFunc( x ): 
    
    #MANNUAL DERIVATIVE THEN TYPE HERE
	return 3*x**2 - 4*x + 3

# Function to find the root 
def newtonRaphson( x ): 
	h = func(x) / derivFunc(x) 
	while abs(h) >= 0.0001: 
		h = func(x)/derivFunc(x) 
		
		# x(i+1) = x(i) - f(x) / f'(x) 
		x = x - h 
	
	print("The value of the root is : ", 
							"%.4f"% x) 

# Driver program to test above 
x0 = -20 # Initial values assumed 
newtonRaphson(x0) 

# This code is contributed by "Sharad_Bhardwaj" 

The value of the root is :  -5.1003


In [10]:
# Python3 code for implementation of Newton 
# Raphson Method for solving equations 

# An example function whose solution 
# is determined using Bisection Method. 
# The function is x **2 - 7*x -7

def func( x ): 
    
    #CHANGE HERE
	return x**5 - 4*x**4 + 2*x**3 + x**2 - x + 10

# Derivative of the above function 
# which is 3*x^x - 2*x 
def derivFunc( x ): 
    
    #MANNUAL DERIVATIVE THEN TYPE HERE
	return 5*x**4 - 16*x**3 + 6*x**2 + 2*x - 1

# Function to find the root 
def newtonRaphson( x ): 
	h = func(x) / derivFunc(x) 
	while abs(h) >= 0.0001: 
		h = func(x)/derivFunc(x) 
		
		# x(i+1) = x(i) - f(x) / f'(x) 
		x = x - h 
	
	print("The value of the root is : ", 
							"%.4f"% x) 

# Driver program to test above 
x0 = 1 # Initial values assumed 
newtonRaphson(x0) 

The value of the root is :  3.2190


<b><h1> Bisection Method</h1> </b> 

In [2]:
def bisection(f,a,b,N):
    '''Approximate solution of f(x)=0 on interval [a,b] by the bisection method.

    Parameters
    ----------
    f : function
        The function for which we are trying to approximate a solution f(x)=0.
    a,b : numbers
        The interval in which to search for a solution. The function returns
        None if f(a)*f(b) >= 0 since a solution is not guaranteed.
    N : (positive) integer
        The number of iterations to implement.

    Returns
    -------
    x_N : number
        The midpoint of the Nth interval computed by the bisection method. The
        initial interval [a_0,b_0] is given by [a,b]. If f(m_n) == 0 for some
        midpoint m_n = (a_n + b_n)/2, then the function returns this solution.
        If all signs of values f(a_n), f(b_n) and f(m_n) are the same at any
        iteration, the bisection method fails and return None.

    Examples
    --------
    >>> f = lambda x: x**2 - x - 1
    >>> bisection(f,1,2,25)
    1.618033990263939
    >>> f = lambda x: (2*x - 1)*(x - 3)
    >>> bisection(f,0,1,10)
    0.5
    '''
    if f(a)*f(b) >= 0:
        print("Bisection method fails.")
        return None
    a_n = a
    b_n = b
    for n in range(1,N+1):
        m_n = (a_n + b_n)/2
        f_m_n = f(m_n)
        if f(a_n)*f_m_n < 0:
            a_n = a_n
            b_n = m_n
        elif f(b_n)*f_m_n < 0:
            a_n = m_n
            b_n = b_n
        elif f_m_n == 0:
            print("Found exact solution.")
            return m_n
        else:
            print("Bisection method fails.")
            return None
    return (a_n + b_n)/2
# CHANGE HERE
f = lambda x: x**3 - 20 #ganti fungsi disini
bisection_answer = bisection(f,1 ,4,3) #bisection(fungsi,batas awal, akhir, iterasi)
print("the final result is = ",bisection_answer)

the final result is =  2.6875


<b><h1> Brent's Method</h1> </b> 

In [1]:
def brents(f, x0, x1, max_iter=50, tolerance=1e-5):
 
    fx0 = f(x0)
    fx1 = f(x1)
 
    assert (fx0 * fx1) <= 0, "Root not bracketed" 
 
    if abs(fx0) < abs(fx1):
        x0, x1 = x1, x0
        fx0, fx1 = fx1, fx0
 
    x2, fx2 = x0, fx0
 
    mflag = True
    steps_taken = 0
 
    while steps_taken < max_iter and abs(x1-x0) > tolerance:
        fx0 = f(x0)
        fx1 = f(x1)
        fx2 = f(x2)
 
        if fx0 != fx2 and fx1 != fx2:
            L0 = (x0 * fx1 * fx2) / ((fx0 - fx1) * (fx0 - fx2))
            L1 = (x1 * fx0 * fx2) / ((fx1 - fx0) * (fx1 - fx2))
            L2 = (x2 * fx1 * fx0) / ((fx2 - fx0) * (fx2 - fx1))
            new = L0 + L1 + L2
 
        else:
            new = x1 - ( (fx1 * (x1 - x0)) / (fx1 - fx0) )
 
        if ((new < ((3 * x0 + x1) / 4) or new > x1) or
            (mflag == True and (abs(new - x1)) >= (abs(x1 - x2) / 2)) or
            (mflag == False and (abs(new - x1)) >= (abs(x2 - d) / 2)) or
            (mflag == True and (abs(x1 - x2)) < tolerance) or
            (mflag == False and (abs(x2 - d)) < tolerance)):
            new = (x0 + x1) / 2
            mflag = True
 
        else:
            mflag = False
 
        fnew = f(new)
        d, x2 = x2, x1
 
        if (fx0 * fnew) < 0:
            x1 = new
        else:
            x0 = new
 
        if abs(fx0) < abs(fx1):
            x0, x1 = x1, x0
 
        steps_taken += 1
 
    return x1, steps_taken
# CHANGE HERE
f = lambda x: x**3 - x**2 - x - 1 #ganti soal

root, steps = brents(f, 1 , 2, tolerance= 1e-7)
print ("root is:", root)
print ("steps taken:", steps)

root is: 1.8392867552141607
steps taken: 23


In [1]:
def brents(f, x0, x1, max_iter=50, tolerance=1e-5):
 
    fx0 = f(x0)
    fx1 = f(x1)
 
    assert (fx0 * fx1) <= 0, "Root not bracketed" 
 
    if abs(fx0) < abs(fx1):
        x0, x1 = x1, x0
        fx0, fx1 = fx1, fx0
 
    x2, fx2 = x0, fx0
 
    mflag = True
    steps_taken = 0
 
    while steps_taken < max_iter and abs(x1-x0) > tolerance:
        fx0 = f(x0)
        fx1 = f(x1)
        fx2 = f(x2)
 
        if fx0 != fx2 and fx1 != fx2:
            L0 = (x0 * fx1 * fx2) / ((fx0 - fx1) * (fx0 - fx2))
            L1 = (x1 * fx0 * fx2) / ((fx1 - fx0) * (fx1 - fx2))
            L2 = (x2 * fx1 * fx0) / ((fx2 - fx0) * (fx2 - fx1))
            new = L0 + L1 + L2
 
        else:
            new = x1 - ( (fx1 * (x1 - x0)) / (fx1 - fx0) )
 
        if ((new < ((3 * x0 + x1) / 4) or new > x1) or
            (mflag == True and (abs(new - x1)) >= (abs(x1 - x2) / 2)) or
            (mflag == False and (abs(new - x1)) >= (abs(x2 - d) / 2)) or
            (mflag == True and (abs(x1 - x2)) < tolerance) or
            (mflag == False and (abs(x2 - d)) < tolerance)):
            new = (x0 + x1) / 2
            mflag = True
 
        else:
            mflag = False
 
        fnew = f(new)
        d, x2 = x2, x1
 
        if (fx0 * fnew) < 0:
            x1 = new
        else:
            x0 = new
 
        if abs(fx0) < abs(fx1):
            x0, x1 = x1, x0
 
        steps_taken += 1
 
    return x1, steps_taken
# CHANGE HERE
f = lambda x: 63.5688*x**3 - 34.37463*x**2 + 0.36 #ganti soal

root, steps = brents(f, -20 , 20, tolerance= 1e-7)
print ("root is:", root)
print ("steps taken:", steps)

root is: 0.5197860049135715
steps taken: 22


<b><h1> Derivative</h1> </b> 

In [16]:
# CHANGE H HERE
def derivative(f,a,method='central',h=0.01):
    '''Compute the difference formula for f'(a) with step size h.

    Parameters
    ----------
    f : function
        Vectorized function of one variable
    a : number
        Compute derivative at x = a
    method : string
        Difference formula: 'forward', 'backward' or 'central'
    h : number
        Step size in difference formula

    Returns
    -------
    float
        Difference formula:
            central: f(a+h) - f(a-h))/2h
            forward: f(a+h) - f(a))/h
            backward: f(a) - f(a-h))/h            
    '''
    if method == 'central':
        return (f(a + h) - f(a - h))/(2*h)
    elif method == 'forward':
        return (f(a + h) - f(a))/h
    elif method == 'backward':
        return (f(a) - f(a - h))/h
    else:
        raise ValueError("Method must be 'central', 'forward' or 'backward'.")

# CHANGE F AND A HERE
f = lambda x: ((x**3)) #ganti soal disini
derivative(f , 1 , method = 'forward', h = 0.5 ) #ganti method disini

4.75

<h1><b> Richardson but unknown method

In [19]:
import numpy

def richardson( f, x, n, h ):
    """Richardson's Extrapolation to approximate  f'(x) at a particular x.

    USAGE:
	d = richardson( f, x, n, h )

    INPUT:
	f	- function to find derivative of
	x	- value of x to find derivative at
	n	- number of levels of extrapolation
	h	- initial stepsize

    OUTPUT:
        numpy float array -  two-dimensional array of extrapolation values.
                             The [n,n] value of this array should be the
                             most accurate estimate of f'(x).

    NOTES:                             
        Based on an algorithm in "Numerical Mathematics and Computing"
        4th Edition, by Cheney and Kincaid, Brooks-Cole, 1999.

    AUTHOR:
        Jonathan R. Senning <jonathan.senning@gordon.edu>
        Gordon College
        February 9, 1999
        Converted ty Python August 2008
    """

    # d[n,n] will contain the most accurate approximation to f'(x).

    d = numpy.array( [[0] * (n + 1)] * (n + 1), float )

    for i in range( n + 1 ):
        d[i,0] = 0.5 * ( f( x + h ) - f( x - h ) ) / h

        powerOf4 = 1  # values of 4^j
        for j in range( 1, i + 1 ):
            powerOf4 = 4 * powerOf4
            d[i,j] = d[i,j-1] + ( d[i,j-1] - d[i-1,j-1] ) / ( powerOf4 - 1 )

        h = 0.5 * h

    return d

f = lambda x: ((5*x*np.exp(-2*x))) #ganti soal disini
richardson(f , 0.35 , 0 , 0.125 )

array([[0.80471304]])

<h1><b> Using sin cos tan in python with degree (not rad) 

In [4]:
import numpy
numpy.sin(numpy.deg2rad(30))

0.49999999999999994

# Gauss Scipy

In [4]:
import numpy
numpy.sin(30)

AttributeError: module 'numpy' has no attribute 'sindeg'

In [3]:
from numpy import array
from scipy.linalg import solve
import numpy as np

def gaussElimination(A,b):
    #A = array([[4,-2,1],[-2,4,-2],[1,-2,4]])
    #b = array([11,-16,17])
    x = solve(A, b)
    print("X1,X2,X3 =",x)

    check = np.dot(A, x) - b
    print("A*x-b harus [0 0 0]")
    print("A*x-b = ", check)
    return x,check

A = array([[1, -2, 1, -3, 1], [2, 1, -3, 1, 2], [-1, -1, -1, -1, -1], [1, 1, 1, -1, -1], [2, -2, 1, -1, 1]])
b = array([1, 15, -3, -1, 0])

x, check = gaussElimination(A, b)

X1,X2,X3 = [ 1.  2. -2. -1.  3.]
A*x-b harus [0 0 0]
A*x-b =  [-8.8817842e-16  0.0000000e+00 -4.4408921e-16 -4.4408921e-16
 -4.4408921e-16]


# Derivative

In [13]:
#real function
def f(x):
    y = x**3 + 2*x**2 - 10*x + 5 #insert eq here
    return y

#Differential eq
def actual_diff_f(x):
    y = 3*x**2 + 4*x - 10 #insert differential equation here
    return y

#Forward
def f_Forward(x,h):
    fh = f(x+h)
    fx = f(x)
    eq = (fh-fx)/h
    return eq

#Backward
def f_Backward(x,h):
    fh = f(x-h)
    fx = f(x)
    eq = (fx-fh)/h
    return eq

#Middle
def f_Middle(x,h):
    fh = f(x+h)
    fx = f(x-h)
    eq = (fh-fx)/(2*h)
    return eq

#Data
x= 1.5
h=0.02

Forward = f_Forward(x,h)
print("using forward method, predicted f'(x):",Forward)
Backward = f_Backward(x,h)
print("using backward method, predicted f'(x):",Backward)
Middle = f_Middle(x,h)
print("using middle method, predicted f'(x):",Middle)
Actual = actual_diff_f(x)
print("actual f'(x):",Actual)

using forward method, predicted f'(x): 2.880400000000094
using backward method, predicted f'(x): 2.6204000000000782
using middle method, predicted f'(x): 2.750400000000086
actual f'(x): 2.75


In [14]:
#real function
def f(x):
    y = x**4 + x**3 + 2*x**2 - 3*x + 10 #insert eq here
    return y

#Differential eq
def actual_diff_f(x):
    y = 4*x**3 + 3*x**2 + 4*x - 3 #insert differential equation here
    return y

#Forward
def f_Forward(x,h):
    fh = f(x+h)
    fx = f(x)
    eq = (fh-fx)/h
    return eq

#Backward
def f_Backward(x,h):
    fh = f(x-h)
    fx = f(x)
    eq = (fx-fh)/h
    return eq

#Middle
def f_Middle(x,h):
    fh = f(x+h)
    fx = f(x-h)
    eq = (fh-fx)/(2*h)
    return eq

#Data
x= 1.7
h= 0.02

Forward = f_Forward(x,h)
print("using forward method, predicted f'(x):",Forward)
Backward = f_Backward(x,h)
print("using backward method, predicted f'(x):",Backward)
Middle = f_Middle(x,h)
print("using middle method, predicted f'(x):",Middle)
Actual = actual_diff_f(x)
print("actual f'(x):",Actual)

using forward method, predicted f'(x): 32.613928000000136
using backward method, predicted f'(x): 31.636311999999833
using middle method, predicted f'(x): 32.12511999999998
actual f'(x): 32.12199999999999
